name: cd-demo
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2 
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
        
    - name: Terraform Init
      run: terraform init
      working-directory: infra/
      
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: infra/
      
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: infra/
  deploy:
  	name:'Deploy to Azure'
  	steps:
    - uses: JimCronqvist/action-ssh@7737f1192ddd8376686e9d6354dea44592c942bf
      name: Execute SSH commmands on remote server
      with:
       hosts: '${{ secrets.REMOTE_USER }}@${{ secrets.HOSTNAME }}'
       privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
       command: |
       	yes|apt-get install docker
       	docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" -p="${{ secrets.DOCKERHUB_PASSWORD }}"
       	docker run -d -p 8080:8080 supriya7/cicd-demo:latest
	